filepath2=r'' # percorso file dei file da far convertire
filepath=r'' #percorso file dei file da far convertire
folder10s=r''#percorso dei file con campionamento a 10 e 2 secondi
folder2s_train=r''#percorso dei file con campionamento a 2 secondi
folder15s=r''#Percorso con tutti i campionamenti
folder2s=r''#percorso con solo 2 secondi di campionamento
folderT=r''#percorso dei file tagliati dopo RC
folderTtrain=r''#percorso dei file tagliati dopo RC
folderPower=r''#percorso dei da cui predire il power
folderPowerTrain=r''#percorso dei file da cui predire il poer
Dati101I=r''#percorso di tutti i 101 file
Dati101Test=r''#percorso di tutti i 101 file
Dati101Train=r''#percorso di tutti i 101 file
DatiSenzaP=r''#percorso con i file senza paralimpici
DatiSenzaPTest=r''#percorso con i file senza paralimpici
DatiSenzaPTrain=r''#percorso con i file senza paralimpici
lista=[0]*16
Test=0
AT=1
RC=2
MinMax=3
max_len=1090
